apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: vsphere-volume-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/vsphere-volume
  finalizers:
  - kubernetes.io/pv-protection
  name: registry-storage
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: registry-storage
    namespace: default
  persistentVolumeReclaimPolicy: Delete
  storageClassName: vsphere-standard
  vsphereVolume:
    fsType: ext4
