---
- name: Create F5 VIPs Openshift
  hosts: localhost
  connection: local
  gather_facts: true

  vars:
    # In my host, I use python3 and the f5-sdk module is installed on it, so I need to set here.
    ansible_python_interpreter: "python3"
    # Define F5 Partition
    F5_partition: 'Common'
    # Setup F5 Big-IP connection parameters
    provider:
      server: '192.168.1.10'
      user: 'admin'
      password: 'adminpwd'
      server_port: 443
      validate_certs: no
    # Define in the lb_instances array each LB instance to be created
    lb_instances: [
      {
        name: 'Master-API',
        port: 6443,
        monitor: true,
        monitor_type: 'master',
        vip: '192.168.1.30',
        # Add the nodes below using either the hostname array OR the IP array. Do not add to both.
        # Add the IP or hostname of the nodes
        node_hostnames: [],
        node_ips: ['192.168.1.110','192.168.1.111','192.168.1.112']
        },
      {
        # Use this for Openshift 3 and Openshift 4
        name: 'Infra-HTTP',
        port: 80,
        monitor: true,
        monitor_type: 'infra',
        vip: '192.168.1.31',
        node_hostnames: [],
        node_ips: ['192.168.1.120','192.168.1.121'],
        },
      {
        # Use this for Openshift 3 and Openshift 4
        name: 'Infra-HTTPS',
        port: 443,
        monitor: true,
        monitor_type: 'infra',
        vip: '192.168.1.31',
        node_hostnames: [],
        node_ips: ['192.168.1.120','192.168.1.121'],
        },
    ]

  tasks:

  - name: Create Master Monitor
    bigip_monitor_https:
      provider: '{{ provider }}'
      partition: '{{F5_partition}}'
      name: '{{item.name}}-monitor'
      parent: 'https'
      send: 'GET /healthz'
    loop: '{{ lb_instances|flatten(levels=1) }}'
    when: item.monitor_type == 'master'
    tags:
      - monitor

  - name: Create Infra Monitor
    bigip_monitor_http:
      provider: '{{ provider }}'
      partition: '{{F5_partition}}'
      name: '{{item.name}}-monitor'
      parent: 'http'
      send: 'GET /healthz'
      ip: '*'
      port: '1936'
    loop: '{{ lb_instances|flatten(levels=1) }}'
    when: item.monitor_type == 'infra'
    tags:
      - monitor

  - name: Create a pool with monitor
    bigip_pool:
      provider: '{{ provider }}'
      partition: '{{F5_partition}}'
      name: '{{item.name}}-pool'
      lb_method: round-robin
      slow_ramp_time: 120
      monitors: '/{{F5_partition}}/{{item.name}}-monitor'
    loop: '{{ lb_instances|flatten(levels=1) }}'
    when: item.monitor
    tags:
      - pool

  - name: Create a pool without monitor
    bigip_pool:
      provider: '{{ provider }}'
      partition: '{{F5_partition}}'
      name: '{{item.name}}-pool'
      lb_method: round-robin
      slow_ramp_time: 120
    loop: '{{ lb_instances|flatten(levels=1) }}'
    when: not item.monitor
    tags:
      - pool

  - name: Add members to pool from hostnames
    bigip_pool_member:
      provider: '{{ provider }}'
      partition: '{{F5_partition}}'
      description: 'Node {{ item.1 }}'
      hostname: '{{ item.1 }}'
      name: '{{ item.1 }}'
      pool: '{{item.0.name}}-pool'
      port: '{{item.0.port}}'
    loop: '{{ lb_instances|subelements("node_hostnames") }}'
    tags:
      - pool

  - name: Add members to pool from IPs
    bigip_pool_member:
      provider: '{{ provider }}'
      partition: '{{F5_partition}}'
      description: 'Node {{ item.1 }}'
      address: '{{ item.1 }}'
      name: '{{ item.1 }}'
      pool: '{{item.0.name}}-pool'
      port: '{{item.0.port}}'
    loop: '{{ lb_instances|subelements("node_ips") }}'
    tags:
      - pool

  - name: Create a Virtual Server (VIP)
    bigip_virtual_server:
      provider: '{{ provider }}'
      partition: '{{F5_partition}}'
      description: 'VIP {{ item.name }}'
      destination: '{{item.vip}}'
      name: '{{ item.name }}-vip'
      pool: '{{ item.name }}-pool'
      port: '{{item.port}}'
      snat: Automap
      type: performance-l4
      profiles:
        - fastL4
    loop: '{{ lb_instances|flatten(levels=1) }}'
    tags:
      - vip

  - name: Warning
    debug:
      msg:
      - "This playbook does not remove pool members from BigIP that are not defined in the arrays. Remove them manually from each pool if required."
