apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: analise-prod
spec:
  limits:
  - max:
      cpu: "8"
      memory: 32Gi
    type: Pod
  - default:
      cpu: 300m
      memory: 256Mi
    defaultRequest:
      cpu: 300m
      memory: 256Mi
    max:
      cpu: 500m
      memory: 1Gi
    type: Container
